routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('noticias','NoticiaController');

app/Autor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Autor extends Model
{
    //
}

app/Noticia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    
    protected $fillable = [
        'titulo', 'fotografia', 'autor_id', 'descripcion'
    ];

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AutorController.php
<?php

namespace App\Http\Controllers;

use App\Autor;
use Illuminate\Http\Request;

class AutorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function show(Autor $autor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function edit(Autor $autor)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Autor $autor)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Autor $autor)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/NoticiaController.php
<?php

namespace App\Http\Controllers;

use App\Noticia;
use App\Autor;
use Illuminate\Http\Request;
use Log;

class NoticiaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Noticia::latest()->paginate(5);
  
        return view('noticias.index',compact('noticias'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $autores = Autor::all();
        return view('noticias.create', compact('autores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo' => 'required'
        ]);

        $path = $request->fotografia->storeAs('fotografías', $request->fotografia->getClientOriginalName());
        Log::debug("Path ".$path);
        
        Log::debug("Request ".$request);
        $noticia = new Noticia($request->all());
       
        $noticia->fotografia = base64_encode(file_get_contents($request->file('fotografia')->path()));
        $noticia->save();
   
        return redirect()->route('noticias.index')
                        ->with('success','Noticia creada con éxito.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function edit(Noticia $noticia)
    {
        $autores = Autor::all();
        return view('noticias.edit',compact('noticia', 'autores'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Noticia $noticia)
    {
        $request->validate([
            'titulo' => 'required'
        ]);
  
        $noticia->update($request->all());
  
        return redirect()->route('noticias.index')
                        ->with('success','Noticia actualizada con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Noticia  $noticia
     * @return \Illuminate\Http\Response
     */
    public function destroy(Noticia $noticia)
    {
        $noticia->delete();
  
        return redirect()->route('noticias.index')
                        ->with('success','Noticia eliminada con éxito.');
    }
}

resources/views/noticias/create.blade.php
@extends('noticias.layout')
  
@section('content')
<div class="row">
    <div class="col-md-12">
        <h2>Crear Noticia</h2>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('noticias.store') }}" method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label>Título:</label>
                <input type="text" name="titulo" class="form-control" placeholder="Título" required>
                <div class="invalid-feedback">
                    Campo obligatorio
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label>Autor</label>
                <select class="form-control" name="autor_id" required>
                    @foreach($autores as $autor)
                        <option value="{{$autor->id}}">{{$autor->nombre}} {{$autor->apellido_paterno}} {{$autor->apellido_materno}}</option>
                    @endforeach
                </select>
                <div class="invalid-feedback">
                    Campo obligatorio
                </div>
          </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label>Descripción</label>
                <textarea class="form-control" name="descripcion" rows="3" required></textarea>
                <div class="invalid-feedback">
                    Campo obligatorio
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="exampleFormControlFile1">Adjuntar imagen</label>
                <input type="file" class="form-control-file" name="fotografia" required>
                <div class="invalid-feedback">
                    Campo obligatorio
                </div>
            </div>
        </div>
        <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a class="btn btn-info" href="{{ route('noticias.index') }}"> Regresar</a>
        </div>
    </div>
   
</form>
@endsection

<script>
(function() {
  'use strict';
  window.addEventListener('load', function() {
    var forms = document.getElementsByClassName('needs-validation');
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

resources/views/noticias/edit.blade.php
@extends('noticias.layout')
   
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="pull-left">
                <h2>Editar Noticia</h2>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('noticias.update',$noticia->id) }}" method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Título:</label>
                    <input type="text" value="{{ $noticia->titulo }}" name="titulo" class="form-control" placeholder="Título" required>
                    <div class="invalid-feedback">
                        Campo obligatorio
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                <label>Autor</label>
                <select class="form-control" name="autor_id" required> 
                    @foreach($autores as $autor)
                        @if($autor->id === $noticia->autor_id)
                            <option selected value="{{$autor->id}}">{{$autor->nombre}} {{$autor->apellido_paterno}} {{$autor->apellido_materno}}</option>
                        @else
                            <option value="{{$autor->id}}">{{$autor->nombre}} {{$autor->apellido_paterno}} {{$autor->apellido_materno}}</option>
                        @endif
                    @endforeach
                </select>
                <div class="invalid-feedback">
                    Campo obligatorio
                </div>
              </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>Descripción</label>
                    <textarea class="form-control" name="descripcion" rows="3" required>{{$noticia->descripcion}}</textarea>
                    <div class="invalid-feedback">
                        Campo obligatorio
                    </div>
                </div>
            </div>
            <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-primary">Editar</button>
                <a class="btn btn-info" href="{{ route('noticias.index') }}"> Regresar</a>
            </div>
        </div>
    </form>
@endsection

<script>
(function() {
  'use strict';
  window.addEventListener('load', function() {
    var forms = document.getElementsByClassName('needs-validation');
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

resources/views/noticias/index.blade.php
@extends('noticias.layout')
 
@section('content')
    <div class="row">
        <div class="col-md-6">
            <h2>Listado de Noticias</h2>
        </div>
        <div class="col-md-6 text-right">
            <a class="btn btn-info" href="{{route('noticias.create')}}"> Crear Noticia </a>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-striped">
        <tr>
            <th width="280px">Noticia</th>
            <th>Descripción</th>
            <th width="280px">Acciones</th>
        </tr>
        @foreach ($noticias as $noticia)
        <tr>
            <td class="text-center">
                <img src="data:image/gif;base64,{{$noticia->fotografia}}" class="img-fluid" alt="Responsive image">
                <br>
                <strong>{{ $noticia->titulo }}</strong>
            </td>
            <td class="align-middle">
                <p>{{ $noticia->descripcion }}</p>            
            </td>
            <td class="align-middle">
                <form action="{{ route('noticias.destroy',$noticia->id) }}" method="POST">

    
                    <a class="btn btn-info" href="{{ route('noticias.edit',$noticia->id) }}">Modificar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $noticias->links() !!}
      
@endsection

resources/views/noticias/layout.blade.php
<!DOCTYPE html>
<html>
	<head>
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>
	<body>
	<nav class="navbar navbar-dark bg-primary mb-4">
  		<a class="navbar-brand">App de Noticias</a>
	</nav>
	<div class="container">
	    @yield('content')
	</div>
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	</body>
</html>